from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1890, 1050)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pic1 = QtWidgets.QLabel(self.centralwidget)
        self.pic1.setGeometry(QtCore.QRect(0, 0, 630, 350))
        self.pic1.setFrameShape(QtWidgets.QFrame.Box)
        self.pic1.setText("")
        self.pic1.setObjectName("pic1")
        self.pic2 = QtWidgets.QLabel(self.centralwidget)
        self.pic2.setGeometry(QtCore.QRect(630, 0, 630, 350))
        self.pic2.setFrameShape(QtWidgets.QFrame.Box)
        self.pic2.setText("")
        self.pic2.setObjectName("pic2")
        self.pic3 = QtWidgets.QLabel(self.centralwidget)
        self.pic3.setGeometry(QtCore.QRect(1260, 0, 630, 350))
        self.pic3.setFrameShape(QtWidgets.QFrame.Box)
        self.pic3.setText("")
        self.pic3.setObjectName("pic3")
        self.pic4 = QtWidgets.QLabel(self.centralwidget)
        self.pic4.setGeometry(QtCore.QRect(0, 350, 630, 350))
        self.pic4.setFrameShape(QtWidgets.QFrame.Box)
        self.pic4.setText("")
        self.pic4.setObjectName("pic4")
        self.pic5 = QtWidgets.QLabel(self.centralwidget)
        self.pic5.setGeometry(QtCore.QRect(630, 350, 630, 350))
        self.pic5.setFrameShape(QtWidgets.QFrame.Box)
        self.pic5.setText("")
        self.pic5.setObjectName("pic5")
        self.pic6 = QtWidgets.QLabel(self.centralwidget)
        self.pic6.setGeometry(QtCore.QRect(1260, 350, 630, 350))
        self.pic6.setFrameShape(QtWidgets.QFrame.Box)
        self.pic6.setText("")
        self.pic6.setObjectName("pic6")
        self.pic7 = QtWidgets.QLabel(self.centralwidget)
        self.pic7.setGeometry(QtCore.QRect(0, 700, 630, 350))
        self.pic7.setFrameShape(QtWidgets.QFrame.Box)
        self.pic7.setText("")
        self.pic7.setObjectName("pic7")
        self.pic8 = QtWidgets.QLabel(self.centralwidget)
        self.pic8.setGeometry(QtCore.QRect(630, 700, 630, 350))
        self.pic8.setFrameShape(QtWidgets.QFrame.Box)
        self.pic8.setText("")
        self.pic8.setObjectName("pic8")
        self.pic9 = QtWidgets.QLabel(self.centralwidget)
        self.pic9.setGeometry(QtCore.QRect(1260, 700, 630, 350))
        self.pic9.setFrameShape(QtWidgets.QFrame.Box)
        self.pic9.setText("")
        self.pic9.setObjectName("pic9")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 60, 75, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1890, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.display1_1)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DOAS PLACEHOLDER TITLE"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))

    def display1_1(self):
        self.pic1.setPixmap(QtGui.QPixmap('C:\\Users\\tonylizj\\Documents\\GitHub\\doas_media\\test1_1.bmp'))
        self.pushButton.deleteLater()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

